name: Create and publish nightly dev Docker image

on:
  # Manual trigger
  workflow_dispatch:
  # At 06:00 AM, on Tuesday, Thursday, and Saturday
  schedule:
  - cron: "0 6 * * TUE,THU,SAT"
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  publish-nightly:
    name: Build, Test, Publish and Deploy nightly Docker image
    runs-on: ubuntu-latest
    #permissions:
    #  contents: read
    #  packages: write
    #  # This is used to complete the identity challenge
    #  # with sigstore/fulcio when running outside of PRs.
    #  id-token: write
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build Smartstore.sln -c Release

    #- name: Test
    #  run: dotnet test Smartstore.sln -c Release --no-restore --no-build
    
    - name: Log in to the GitHub Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    #- name: Log in to Docker Hub
    #  uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #  with:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Publish and Push for Linux
      run: | 
        dotnet publish src/Smartstore.Web/Smartstore.Web.csproj -c Release -o ./build/artifacts/Community.nightly.linux-x64 --no-restore --no-build --no-self-contained
        docker build --build-arg VERSION=nightly -f NoBuild.Dockerfile -t ghcr.io/smartstore/smartstore-linux:nightly .
        docker push ghcr.io/smartstore/smartstore-linux:nightly
        #docker build --build-arg VERSION=nightly -f NoBuild.Dockerfile -t smartstore/smartstore-linux:nightly .
        #docker push smartstore/smartstore-linux:nightly

    #- name: Publish and Push for Windows
    #  run: | 
    #    dotnet publish src/Smartstore.Web/Smartstore.Web.csproj -c Release -o ./build/artifacts/Community.nightly.win-x64 --no-restore --no-build --no-self-contained
    #    docker build --build-arg VERSION=nightly -f Nano.Dockerfile -t ghcr.io/smartstore/smartstore-windows:nightly .
    #    docker push ghcr.io/smartstore/smartstore-windows:nightly
